# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false  
  config.vm.box_url = "http://architech-repo.cloudapp.net:8761/vagrant/dotcms_ubuntu_mysql_3.3.json"
  config.vm.box = "architech/dotcms-3.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 3306, host: 3308
  config.vm.network "private_network", ip: "192.168.56.210"
  

   config.vm.provider "virtualbox" do |vb|
  #    Display the VirtualBox GUI when booting the machine
  #    vb.gui = true
  #
      vb.memory = "2048"
   end

end
